model:
  name: 'osnet_ain_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['uet_reid']
  targets: ['uet_reid']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/osnet_ain_x1_0_market1501_softmax_cosinelr'

loss:
  name: 'softmax'
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  lr: 0.0015
  max_epoch: 15
  batch_size: 64
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'cosine'
  print_freq: '80'
  start_epoch: 11
test:
  batch_size: 150
  dist_metric: 'cosine'
  normalize_feature: False
  evaluate: False
  eval_freq: 5
  rerank: False
  #visrank: True
  #visrank_topk: 10
  #ranks: [1, 5, 10]
